# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 704)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.searchCardLabel = QtWidgets.QLabel(self.centralWidget)
        self.searchCardLabel.setGeometry(QtCore.QRect(280, 10, 81, 16))
        self.searchCardLabel.setObjectName("searchCardLabel")
        self.suggestionLabel = QtWidgets.QLabel(self.centralWidget)
        self.suggestionLabel.setGeometry(QtCore.QRect(280, 70, 81, 16))
        self.suggestionLabel.setObjectName("suggestionLabel")
        self.testHandButton = QtWidgets.QPushButton(self.centralWidget)
        self.testHandButton.setGeometry(QtCore.QRect(610, 110, 131, 41))
        self.testHandButton.setObjectName("testHandButton")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(535, 30, 71, 271))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.suggestionList = QtWidgets.QListWidget(self.centralWidget)
        self.suggestionList.setGeometry(QtCore.QRect(280, 90, 261, 251))
        self.suggestionList.setObjectName("suggestionList")
        self.monsterList = QtWidgets.QListWidget(self.centralWidget)
        self.monsterList.setGeometry(QtCore.QRect(10, 370, 191, 271))
        self.monsterList.setObjectName("monsterList")
        self.monsterLabel = QtWidgets.QLabel(self.centralWidget)
        self.monsterLabel.setGeometry(QtCore.QRect(10, 350, 91, 21))
        self.monsterLabel.setObjectName("monsterLabel")
        self.cardNameBox = QtWidgets.QLineEdit(self.centralWidget)
        self.cardNameBox.setGeometry(QtCore.QRect(280, 30, 261, 31))
        self.cardNameBox.setObjectName("cardNameBox")
        self.spellList = QtWidgets.QListWidget(self.centralWidget)
        self.spellList.setGeometry(QtCore.QRect(200, 370, 191, 271))
        self.spellList.setObjectName("spellList")
        self.spellLabel = QtWidgets.QLabel(self.centralWidget)
        self.spellLabel.setGeometry(QtCore.QRect(200, 350, 41, 21))
        self.spellLabel.setObjectName("spellLabel")
        self.trapList = QtWidgets.QListWidget(self.centralWidget)
        self.trapList.setGeometry(QtCore.QRect(390, 370, 191, 271))
        self.trapList.setObjectName("trapList")
        self.trapLabel = QtWidgets.QLabel(self.centralWidget)
        self.trapLabel.setGeometry(QtCore.QRect(390, 350, 91, 21))
        self.trapLabel.setObjectName("trapLabel")
        self.extraList = QtWidgets.QListWidget(self.centralWidget)
        self.extraList.setGeometry(QtCore.QRect(580, 370, 191, 271))
        self.extraList.setObjectName("extraList")
        self.extraLabel = QtWidgets.QLabel(self.centralWidget)
        self.extraLabel.setGeometry(QtCore.QRect(580, 350, 91, 21))
        self.extraLabel.setObjectName("extraLabel")
        self.totalMainLabel = QtWidgets.QLabel(self.centralWidget)
        self.totalMainLabel.setGeometry(QtCore.QRect(580, 310, 91, 31))
        self.totalMainLabel.setObjectName("totalMainLabel")
        self.duelButton = QtWidgets.QPushButton(self.centralWidget)
        self.duelButton.setGeometry(QtCore.QRect(610, 70, 131, 41))
        self.duelButton.setObjectName("duelButton")
        self.deckNameBox = QtWidgets.QLineEdit(self.centralWidget)
        self.deckNameBox.setGeometry(QtCore.QRect(590, 30, 173, 30))
        self.deckNameBox.setObjectName("deckNameBox")
        self.deckNameLabel = QtWidgets.QLabel(self.centralWidget)
        self.deckNameLabel.setGeometry(QtCore.QRect(590, 0, 91, 31))
        self.deckNameLabel.setObjectName("deckNameLabel")
        self.monsterCount = QtWidgets.QSpinBox(self.centralWidget)
        self.monsterCount.setGeometry(QtCore.QRect(120, 350, 31, 21))
        self.monsterCount.setAlignment(QtCore.Qt.AlignCenter)
        self.monsterCount.setReadOnly(True)
        self.monsterCount.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monsterCount.setObjectName("monsterCount")
        self.spellCount = QtWidgets.QSpinBox(self.centralWidget)
        self.spellCount.setGeometry(QtCore.QRect(300, 350, 31, 21))
        self.spellCount.setAlignment(QtCore.Qt.AlignCenter)
        self.spellCount.setReadOnly(True)
        self.spellCount.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spellCount.setObjectName("spellCount")
        self.trapCount = QtWidgets.QSpinBox(self.centralWidget)
        self.trapCount.setGeometry(QtCore.QRect(500, 350, 31, 21))
        self.trapCount.setAlignment(QtCore.Qt.AlignCenter)
        self.trapCount.setReadOnly(True)
        self.trapCount.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.trapCount.setObjectName("trapCount")
        self.extraCount = QtWidgets.QSpinBox(self.centralWidget)
        self.extraCount.setGeometry(QtCore.QRect(680, 350, 31, 21))
        self.extraCount.setAlignment(QtCore.Qt.AlignCenter)
        self.extraCount.setReadOnly(True)
        self.extraCount.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.extraCount.setObjectName("extraCount")
        self.totalCount = QtWidgets.QSpinBox(self.centralWidget)
        self.totalCount.setGeometry(QtCore.QRect(680, 310, 31, 31))
        self.totalCount.setAlignment(QtCore.Qt.AlignCenter)
        self.totalCount.setReadOnly(True)
        self.totalCount.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.totalCount.setObjectName("totalCount")
        self.cardNameLabel = QtWidgets.QLabel(self.centralWidget)
        self.cardNameLabel.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.cardNameLabel.setObjectName("cardNameLabel")
        self.effectLabel = QtWidgets.QLabel(self.centralWidget)
        self.effectLabel.setGeometry(QtCore.QRect(10, 110, 91, 31))
        self.effectLabel.setObjectName("effectLabel")
        self.effectBox = QtWidgets.QTextEdit(self.centralWidget)
        self.effectBox.setGeometry(QtCore.QRect(10, 140, 241, 201))
        self.effectBox.setReadOnly(True)
        self.effectBox.setObjectName("effectBox")
        self.cardTypeLabel = QtWidgets.QLabel(self.centralWidget)
        self.cardTypeLabel.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.cardTypeLabel.setObjectName("cardTypeLabel")
        self.typeLabel = QtWidgets.QLabel(self.centralWidget)
        self.typeLabel.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.typeLabel.setObjectName("typeLabel")
        self.attributeLabel = QtWidgets.QLabel(self.centralWidget)
        self.attributeLabel.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.attributeLabel.setObjectName("attributeLabel")
        self.levelLabel = QtWidgets.QLabel(self.centralWidget)
        self.levelLabel.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.levelLabel.setObjectName("levelLabel")
        self.cardTypeBox = QtWidgets.QLineEdit(self.centralWidget)
        self.cardTypeBox.setGeometry(QtCore.QRect(80, 30, 171, 21))
        self.cardTypeBox.setReadOnly(True)
        self.cardTypeBox.setObjectName("cardTypeBox")
        self.typeBox = QtWidgets.QLineEdit(self.centralWidget)
        self.typeBox.setGeometry(QtCore.QRect(80, 50, 171, 21))
        self.typeBox.setReadOnly(True)
        self.typeBox.setObjectName("typeBox")
        self.attributeBox = QtWidgets.QLineEdit(self.centralWidget)
        self.attributeBox.setGeometry(QtCore.QRect(80, 70, 171, 21))
        self.attributeBox.setReadOnly(True)
        self.attributeBox.setObjectName("attributeBox")
        self.levelBox = QtWidgets.QLineEdit(self.centralWidget)
        self.levelBox.setGeometry(QtCore.QRect(80, 90, 171, 21))
        self.levelBox.setReadOnly(True)
        self.levelBox.setObjectName("levelBox")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 780, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad_Deck = QtWidgets.QAction(MainWindow)
        self.actionLoad_Deck.setObjectName("actionLoad_Deck")
        self.actionSave_Deck = QtWidgets.QAction(MainWindow)
        self.actionSave_Deck.setObjectName("actionSave_Deck")
        self.actionInstructions_2 = QtWidgets.QAction(MainWindow)
        self.actionInstructions_2.setObjectName("actionInstructions_2")
        self.menuFile.addAction(self.actionLoad_Deck)
        self.menuFile.addAction(self.actionSave_Deck)
        self.menuHelp.addAction(self.actionInstructions_2)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Create Your Deck"))
        self.searchCardLabel.setText(_translate("MainWindow", "Search card:"))
        self.suggestionLabel.setText(_translate("MainWindow", "Suggestions:"))
        self.testHandButton.setText(_translate("MainWindow", "Test Hand"))
        self.monsterLabel.setText(_translate("MainWindow", "Monsters:"))
        self.spellLabel.setText(_translate("MainWindow", "Spells:"))
        self.trapLabel.setText(_translate("MainWindow", "Traps:"))
        self.extraLabel.setText(_translate("MainWindow", "Extra:"))
        self.totalMainLabel.setText(_translate("MainWindow", "Total Main:"))
        self.duelButton.setText(_translate("MainWindow", "Duel"))
        self.deckNameLabel.setText(_translate("MainWindow", "Deck Name:"))
        self.cardNameLabel.setText(_translate("MainWindow", "Card Name"))
        self.effectLabel.setText(_translate("MainWindow", "Effect:"))
        self.cardTypeLabel.setText(_translate("MainWindow", "Card Type:"))
        self.typeLabel.setText(_translate("MainWindow", "Type:"))
        self.attributeLabel.setText(_translate("MainWindow", "Attribute:"))
        self.levelLabel.setText(_translate("MainWindow", "Level:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad_Deck.setText(_translate("MainWindow", "Load Deck"))
        self.actionSave_Deck.setText(_translate("MainWindow", "Save Deck"))
        self.actionInstructions_2.setText(_translate("MainWindow", "Instructions"))

